Problem 1

In [ ]:
# Import numpy and matplotlib ONLY
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
x = np.array([[2, 3], [4,1], [-4,-1], [-1,-3]])
x

array([[ 2,  3],
       [ 4,  1],
       [-4, -1],
       [-1, -3]])

In [ ]:
m1 = x[:2].mean(axis=0)
m1

array([3., 2.])

In [ ]:
m2 = x[-2:].mean(axis=0)
m2

array([-2.5, -2. ])

In [ ]:
x[0] @ x[0].T # ~~> this gives "13" as a scalar value, but we want a result matrix
x[0].reshape(2,1) @ x[0].reshape(1,2) # then will need to subtract the mean from every value 
(x[0]-m1).reshape(2,1) @ (x[0]-m1).reshape(1,2) # this covers 1st point, need to add the values for point 2 as well

array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
s1 = (x[0]-m1).reshape(2,1) @ (x[0]-m1).reshape(1,2) + (x[1]-m1).reshape(2,1) @ (x[1]-m1).reshape(1,2)
s1

array([[ 2., -2.],
       [-2.,  2.]])

In [ ]:
s2 = (x[2]-m2).reshape(2,1) @ (x[2]-m2).reshape(1,2) + (x[3]-m2).reshape(2,1) @ (x[3]-m2).reshape(1,2)
s2

array([[ 4.5, -3. ],
       [-3. ,  2. ]])

In [ ]:
sw = s1+s2
sw

array([[ 6.5, -5. ],
       [-5. ,  4. ]])

In [ ]:
sw_inv = np.linalg.inv(sw)
sw_inv

array([[4. , 5. ],
       [5. , 6.5]])

In [ ]:
w = sw_inv @ (m1-m2)
w

array([42. , 53.5])

In [ ]:
#In the problem, we are asked to multiply the value of w by a constant k=0.1
w = 0.1 * (sw_inv @ (m1-m2))
w # would then get w0 but in this example it is equal to 0 because the boundary is passing by the origin

array([4.2 , 5.35])

Problem 3

In [ ]:
x = np.array([[7, 8], [9,6], [1,4], [4,2]])
x

array([[7, 8],
       [9, 6],
       [1, 4],
       [4, 2]])

In [ ]:
m1 = x[:2].mean(axis=0)
m1

array([8., 7.])

In [ ]:
m2 = x[-2:].mean(axis=0)
m2

array([2.5, 3. ])

In [ ]:
s1 = (x[0]-m1).reshape(2,1) @ (x[0]-m1).reshape(1,2) + (x[1]-m1).reshape(2,1) @ (x[1]-m1).reshape(1,2)
s1

array([[ 2., -2.],
       [-2.,  2.]])

In [ ]:
s2 = (x[2]-m2).reshape(2,1) @ (x[2]-m2).reshape(1,2) + (x[3]-m2).reshape(2,1) @ (x[3]-m2).reshape(1,2)
s2

array([[ 4.5, -3. ],
       [-3. ,  2. ]])

In [ ]:
sw = s1+s2
sw

array([[ 6.5, -5. ],
       [-5. ,  4. ]])

In [ ]:
sw_inv = np.linalg.inv(sw)
sw_inv

array([[4. , 5. ],
       [5. , 6.5]])

In [ ]:
w = 0.1 * sw_inv @ (m1-m2)
w

array([4.2 , 5.35])

In [ ]:
mid_point = (m1+m2)/2
w0 = -1 * (w.T @ mid_point)
w0
#Thus the weight vector = [42, 53.5, -488]

-48.800000000000026

Problem 4

In [ ]:
wa = np.array([-1,1])

In [ ]:
wb = np.array([1,1])

In [ ]:
c1 = np.array([[1,4],[2,3],[3,2]])
c1

array([[1, 4],
       [2, 3],
       [3, 2]])

In [ ]:
c2 = np.array([[2,5],[3,4],[4,3]])
c2

array([[2, 5],
       [3, 4],
       [4, 3]])

In [ ]:
m1 = c1.mean(axis=0)
m1

array([2., 3.])

In [ ]:
m2 = c2.mean(axis=0)
m2

array([3., 4.])

In [ ]:
# trying for wa
wa @ m1 # projected mean = dot product

1.0

In [ ]:
wa @ m2 # subtracting proj mean of m1 and m2 = 0, making J(w)=0 which is bad
#we need to maximize the distance between means NOT make it 0

1.0

In [ ]:
# trying for wb
wb @ m1

5.0

In [ ]:
wb @ m2

7.0

In [ ]:
# will project each point on the weight vector, then will calculate distance from this point to projected mean
[((i @ wb) - (wb @ m1))**2 for i in c1]
#this makes s1^2=0
[((i @ wb) - (wb @ m2))**2 for i in c2]
#this makes s2^2=0

jw = ((wb @ m1) -(wb @ m2))**2 / 0 # ~~> if run, would give runtime error

<ipython-input-32-4e5f82855357>:7: RuntimeWarning: divide by zero encountered in double_scalars
  jw = ((wb @ m1) -(wb @ m2))**2 / 0 # ~~> if run, would give runtime error
