**Problem 1**

*   p = 6



In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 5, 6])
x

array([1, 2, 5, 6])

In [ ]:
x_tilda = np.concatenate((x.reshape(4,1), np.ones((4,1))), axis=1) # ~~> converting X into ~X (X tilda)
# NB: axis=0 means concatenating rows, axis=1 means concatenating columns (default is 0)
x_tilda

array([[1., 1.],
       [2., 1.],
       [5., 1.],
       [6., 1.]])

In [ ]:
targets = np.array([-1,-1,1,1]).reshape(4,1)
targets

array([[-1],
       [-1],
       [ 1],
       [ 1]])

In [ ]:
w = np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ targets
w
# first element is w1 and second is w0 (w node)

array([[ 0.47058824],
       [-1.64705882]])

*   p = 20

In [ ]:
x = np.array([1, 2, 5, 20])
x

array([ 1,  2,  5, 20])

In [ ]:
x_tilda = np.concatenate((x.reshape(4,1), np.ones((3,1))), axis=1) 
x_tilda

ValueError: ignored

In [ ]:
targets = np.array([-1,-1,1,1]).reshape(4,1)
targets

In [ ]:
w = np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ targets
w

**Problem 2**

In [ ]:
x2 = np.array([[1,1],[5,-5],[-1,-1],[-5,5]])
x2

In [ ]:
x2.shape

In [ ]:
x2_tilda = np.concatenate((x2, np.ones((4,1))), axis=1) 
x2_tilda

In [ ]:
targets2 = np.array([1,-1,1,-1]).reshape(4,1)
targets2

In [ ]:
w2 = np.linalg.inv(x2_tilda.T @ x2_tilda) @ x2_tilda.T @ targets2
w2
# result of zero means that there exists no solution to this problem